# Generated by Django 5.0.3 on 2024-03-21 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание категории', null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название магазина', max_length=50, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание магазина', verbose_name='Описание')),
                ('open_time', models.TimeField(help_text='Время начала работы магазина', verbose_name='Время открытия')),
                ('close_time', models.TimeField(help_text='Время окончания работы магазина', verbose_name='Время закрытия')),
                ('the_cost_of_delivery', models.DecimalField(decimal_places=2, help_text='Стоимость доставки заказа', max_digits=10, verbose_name='Стоимость доставки')),
                ('minimum_order', models.DecimalField(decimal_places=2, help_text='Минимальная сумма заказа', max_digits=10, verbose_name='Мин заказ')),
                ('maximum_distance_without_extra_charge', models.DecimalField(decimal_places=2, help_text='Максимальное расстояние для бесплатной доставки', max_digits=10, verbose_name='Мак расстояние без платы')),
                ('address', models.CharField(help_text='Адрес магазина', max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, help_text='Номер телефона магазина', max_length=12, null=True, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Маркет',
                'verbose_name_plural': 'Маркеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Изображение продукта', upload_to='products/', verbose_name='Изображение')),
                ('code', models.CharField(help_text='Код продукта', max_length=255, verbose_name='Код')),
                ('name', models.CharField(help_text='Название продукта', max_length=255, verbose_name='Название')),
                ('brand', models.CharField(blank=True, help_text='Бренд продукта', max_length=255, null=True, verbose_name='Бренд')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена продукта', max_digits=10, verbose_name='Цена')),
                ('stock', models.IntegerField(blank=True, help_text='Доступное количество продукта на складе', null=True, verbose_name='Остаток на складе')),
                ('description', models.TextField(blank=True, help_text='Описание продукта', null=True, verbose_name='Описание')),
                ('calories', models.FloatField(blank=True, help_text='Количество калорий в порции продукта', null=True, verbose_name='Калории')),
                ('fat', models.FloatField(blank=True, help_text='Количество жиров в порции продукта', null=True, verbose_name='Жиры')),
                ('carbohydrates', models.FloatField(blank=True, help_text='Количество углеводов в порции продукта', null=True, verbose_name='Углеводы')),
                ('protein', models.FloatField(blank=True, help_text='Количество белков в порции продукта', null=True, verbose_name='Белки')),
                ('fiber', models.FloatField(blank=True, help_text='Количество пищевых волокон в порции продукта', null=True, verbose_name='Пищевые волокна')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('category', models.ForeignKey(help_text='Категория продукта', on_delete=django.db.models.deletion.CASCADE, to='markets.category', verbose_name='Категория')),
                ('market', models.ForeignKey(help_text='Магазин продукта', on_delete=django.db.models.deletion.CASCADE, to='markets.market', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-created_at'],
            },
        ),
    ]
