# Generated by Django 5.0.3 on 2024-03-21 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название магазина', max_length=50, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание магазина', verbose_name='Описание')),
                ('open_time', models.TimeField(help_text='Время начала работы магазина', verbose_name='Время открытия')),
                ('close_time', models.TimeField(help_text='Время окончания работы магазина', verbose_name='Время закрытия')),
                ('the_cost_of_delivery', models.DecimalField(decimal_places=2, help_text='Стоимость доставки заказа', max_digits=10, verbose_name='Стоимость доставки')),
                ('minimum_order', models.DecimalField(decimal_places=2, help_text='Минимальная сумма заказа', max_digits=10, verbose_name='Мин заказ')),
                ('maximum_distance_without_extra_charge', models.DecimalField(decimal_places=2, help_text='Максимальное расстояние для бесплатной доставки', max_digits=10, verbose_name='Мак расстояние без платы')),
                ('address', models.CharField(help_text='Адрес магазина', max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, help_text='Номер телефона магазина', max_length=12, null=True, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Регистрация Маркета',
                'verbose_name_plural': 'Регистрация Маркетов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Текст сообщения в чате', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('account', models.ForeignKey(help_text='Аккаунт, к которому относится чат', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Чат поддержки',
                'verbose_name_plural': 'Чаты поддержки',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, help_text='Статус прочтения уведомления', verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('chat_support', models.ForeignKey(help_text='Чат поддержки, откуда пришло уведомление', on_delete=django.db.models.deletion.CASCADE, to='support.chatsupport', verbose_name='Чат поддержки')),
                ('support_account', models.ForeignKey(help_text='Аккаунт службы поддержки, к которому относится уведомление', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт поддержки')),
            ],
            options={
                'verbose_name': 'Уведомление поддержки',
                'verbose_name_plural': 'Уведомления поддержки',
                'ordering': ['-created_at'],
            },
        ),
    ]
